-- DROP DATABASE cd_datenbank;
CREATE DATABASE IF NOT EXISTS cd_datenbank  DEFAULT CHARACTER SET utf8mb4  DEFAULT COLLATE utf8mb4_unicode_ci;
USE cd_datenbank;

CREATE TABLE Interpreten (
    InterpretID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Interpret   VARCHAR(100) NOT NULL
);

CREATE TABLE Musikrichtung (
    MRID          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Musikrichtung VARCHAR(100) NOT NULL
);

CREATE TABLE CD (
    CDNr         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CDName       VARCHAR(100) NOT NULL,
    IntNr  INT UNSIGNED,
    MRNr INT UNSIGNED,  
	FOREIGN KEY (IntNr) REFERENCES Interpreten (InterpretID),
    FOREIGN KEY (MRNr) REFERENCES Musikrichtung (MRID)
);

CREATE TABLE Titel (
    CDNr        INT UNSIGNED NOT NULL,
    TitelNr     INT UNSIGNED NOT NULL,
    Titel       VARCHAR(255) NOT NULL,
    IntNr INT UNSIGNED NOT NULL,
    Beurteilung DECIMAL (3,2),
    PRIMARY KEY (CDNr, TitelNr),
    FOREIGN KEY (CDNr) REFERENCES CD (CDNr),
    FOREIGN KEY (IntNr) REFERENCES Interpreten (InterpretID)
);